### ISSUE TITLE
Cannot find the code from Opera

### ISSUE THREAD

**Issue by ygzhu** [zen-star/DDT_SSOD_AAAI22#1]
Thanks for your contribution of the SSOD! You have mentioned that the algorithm has been implemented by [Opera](https://github.com/hikvision-research/opera), but I cannot find the implementation in the Opera. When will you release the code?

**Comment by zen-star** [comment]
Code is ready in the private version of Opera. It will be released after going through the examination of our company.

**Comment by zen-star** [comment]
Code is ready in the private version of Opera. It will be released after going through the examination of our company.
